import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from 'fs';

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const dev = (process.argv[2] === "dev");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  outfile: dev ? "main.js" : "dist/main.js",
  bundle: true,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: dev ? "inline" : false,
  minify: dev ? false : true,
  treeShaking: true,
  loader: {
    '.svg': 'text'
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
});

if (dev) {
  await context.watch();
} else {
  await context.rebuild();
  fs.copyFileSync('./manifest.json', './dist/manifest.json');
  if (fs.existsSync('./styles.css')) {
    fs.copyFileSync('./styles.css', './dist/styles.css');
  }
  process.exit(0);
}
